# /.Taskfile.yml
#
# WHAT: This is the public API for the project's automation framework. It is a
#       transparent facade that proxies all commands to the real implementation
#       located in the ./factory directory.
# WHY:  This provides a single, self-documenting entry point for all developers,
#       fulfilling our "Taskfile as the Public API" principle.

version: '3'

# The dotenv declaration MUST live in this top-level file.
dotenv: [".env"]

tasks:
  # The default task explicitly calls the 'default' task from the factory's
  # Taskfile, ensuring the formatted menu is always displayed.
  default:
    desc: "Displays the main project command menu."
    silent: true
    cmds:
      - task --dir ./factory default

  # ---------------------------------------------------------------------------
  # PROXY TASKS (The Public API)
  # Each task below is a simple proxy that calls the real task inside the
  # factory. The description is copied for discoverability (`task --list`),
  # and {{.CLI_ARGS}} ensures all arguments are passed through.
  # ---------------------------------------------------------------------------

  task-start:
    desc: "ACTION: Initiate a new task (e.g., git checkout -b new-feature)."
    cmds:
      - task --dir ./factory task-start -- {{.CLI_ARGS}}

  context:
    desc: "VIEW: Generate context for a specific goal (commit, pr, verify, export-*)."
    cmds:
      - task --dir ./factory context -- {{.CLI_ARGS}}

  run:
    desc: "ACTION: Execute the application locally on your machine."
    cmds:
      - task --dir ./factory run -- {{.CLI_ARGS}}

  commit:
    desc: "ACTION: Save all local changes into a new commit (e.g., git commit)."
    cmds:
      - task --dir ./factory commit -- {{.CLI_ARGS}}

  task-finish:
    desc: "ACTION: Finalize a task (e.g., create a pull request)."
    cmds:
      - task --dir ./factory task-finish -- {{.CLI_ARGS}}

  build:
    desc: "ACTION: Compile source code and create a build artifact."
    cmds:
      - task --dir ./factory build -- {{.CLI_ARGS}}

  test:
    desc: "ACTION: Run the application's full suite of automated tests."
    cmds:
      - task --dir ./factory test -- {{.CLI_ARGS}}

  analyze:
    desc: "ACTION: Inspect code for quality, style, and vulnerabilities."
    cmds:
      - task --dir ./factory analyze -- {{.CLI_ARGS}}

  release:
    desc: "ACTION: Create and publish a new versioned release artifact."
    cmds:
      - task --dir ./factory release -- {{.CLI_ARGS}}

  deploy:
    desc: "ACTION: Deploys the application to the cloud."
    cmds:
      - task --dir ./factory deploy -- {{.CLI_ARGS}}

  provision:
    desc: "GUIDE: Shows setup checklist for cloud infrastructure."
    cmds:
      - task --dir ./factory provision -- {{.CLI_ARGS}}

  verify:
    desc: "VIEW: Check that provisioned infrastructure is healthy."
    cmds:
      - task --dir ./factory verify -- {{.CLI_ARGS}}

  destroy:
    desc: "ACTION: Shows checklist for tearing down all infrastructure."
    cmds:
      - task --dir ./factory destroy -- {{.CLI_ARGS}}

  deps-update:
    desc: "ACTION: Update third-party dependencies to their latest versions."
    cmds:
      - task --dir ./factory deps-update -- {{.CLI_ARGS}}

  clean:
    desc: "ACTION: Remove all local temporary files and build artifacts."
    cmds:
      - task --dir ./factory clean -- {{.CLI_ARGS}}
