# tasks/_analyze.yml
version: '3'
tasks:
  analyze:
    desc: "(Info) Explains that this is a placeholder for code analysis."
    silent: true
    cmds:
      - |
        echo
        echo "--> INFO: This is a placeholder for a code analysis task."
        echo "    The original implementation can be found in the git history if needed."
        echo
