# tasks/_context.yml
# WHAT: This file is the facade for all context-generation commands.
# WHY:  It provides a single, consistent helper task that forwards all
#       arguments to the main context controller script.

version: '3'

tasks:
  # This single helper task is called by all `context:*` tasks in the root Taskfile.
  # It receives the specific mode (e.g., 'commit', 'export-code') via CLI_ARGS.
  helper:
    internal: true
    cmds:
      - ./scripts/context.sh {{.CLI_ARGS}}