# tasks/_run.yml
# Implements the 'run' command to display an informational message.

version: '3'

tasks:
  run:
    desc: "(Info) Explains why there is no local run command for this project."
    silent: true
    cmds:
      - |
        echo
        echo "--> INFO: No 'run' action is defined for this project."
        echo "    This repository contains an automation framework and development"
        echo "    environment, not a runnable application."
        echo
